
export module STORAGE_KEY {
  let COUNTRY_PREFIX_KEY = 'sg-';
  let SESSION_STORAGE_PREFIX_KEY = 'ss-';
  let LOCAL_STORAGE_PREFIX_KEY = 'ls-';

  export let CREATING_EVENT_LOCAL_STORAGE_KEY = COUNTRY_PREFIX_KEY + LOCAL_STORAGE_PREFIX_KEY + 'event';
  export let CATEGORIES_SESSION_STORAGE_KEY = COUNTRY_PREFIX_KEY + LOCAL_STORAGE_PREFIX_KEY + 'category';
  export let BANKS_SESSION_STORAGE_KEY = COUNTRY_PREFIX_KEY + LOCAL_STORAGE_PREFIX_KEY + 'banks';

  // homepage key
  export let DISPLAY_BANNER_HOMEPAGE = 'display_banner_homepage';
  export let CATEGORIES_SEARCH_SESSION_STORAGE_KEY = COUNTRY_PREFIX_KEY + LOCAL_STORAGE_PREFIX_KEY + 'categories';
  export let TOKEN_STORAGE_KEY = COUNTRY_PREFIX_KEY + LOCAL_STORAGE_PREFIX_KEY + 'token';
}

